# Generated by Django 4.0 on 2022-01-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_uni', '0001_initial'),
        ('faculties', '0002_assessment_course_assessmentgrade_assessment_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, to='auth_uni.Student'),
        ),
    ]
